### PR TITLE
Cleaning up dead code

### PR DESCRIPTION
**Pull request by Theodlz**
Jokes aside, this PR does a few things:
- remove a lot of unused imports
- remove some unused methods
- introduce numba to speed-up methods that can be speed up as is (some refactor could allow us to use it in many more functions
- lint some files
- remove unused arguments from some methods
- remove a bunch of unused variables within methods

The reviewer should **carefully** test this, but the changes should be very minimal

### CODE REVIEW

**Comment by Theodlz** [comment]
btw might want to retire 3.8 testing in favor of 3.12, or just add 3.12

**Comment by Theodlz** [comment]
tests not working locally either (incorrect imports of MOCpy in a few places). Fixing it rn

**Comment by Theodlz** [comment]
I found myself having to remove a lot of stuff that did seem relevant in `gwemopt.io.read_skymap()`, because it was creating this `moc_keeps` variable to pass to mocpy's `MOC.probabilities_in_multiordermap()` in `gwemopt.tiles.compute_tiles_map()`, except that MOCpy doesn't take that as an argument anymore?

A little odd, not sure what it does

**Comment by Theodlz** [comment]
> @mcoughlin any idea why the CI doesn't run by default?

let me know if you've experienced that before, no idea how to fix it

**Comment by Theodlz** [comment]
ok some unexistent CI runs where set in the branch rules. Removed that but still not running. Looks like there is a schedule set in the CI, maybe that's why? Like it only runs it at a specific time so these can't run?

**Comment by mcoughlin** [comment]
Idk I would have thought I copied this from skyportal but @robertdstein had tried to improve this.

**Comment by Theodlz** [comment]
ah... github had turned of the CI on this repo for lack of activity... except it's not really clearly flagged...

**Comment by Theodlz** [comment]
Had to resolve some conflicts with main @mcoughlin, and some of them deleted some code which I didn't, so might want to look at my latest commit to double check that. Otherwise, this should be mergeable once green :)

**Comment by mcoughlin** [comment]
@Theodlz sorry a few more conflicts maybe.

**Pull request merged**
